import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { ArrowRight } from "lucide-react";
import AIDashboard from "@/components/AIDashboard";
import { clientoryAppUrl } from "@/lib/clientory-app-url";

const Hero = () => {
  return (
    <section className="relative min-h-[90vh] flex items-center justify-center overflow-hidden">
      {/* Subtle gradient glow */}
      <div className="absolute inset-0 bg-gradient-glow" />
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[600px] rounded-full bg-primary/5 blur-[100px] animate-glow-pulse" />

      <div className="container relative z-10 px-6 py-16">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, ease: [0.25, 0.4, 0.25, 1] }}
          className="max-w-4xl mx-auto text-center">
          
          {/* Badge */}
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.2, duration: 0.5 }}
            className="inline-flex items-center gap-2 px-4 py-2 mb-10 rounded-full border border-border bg-muted/50 backdrop-blur-sm">
            
            <span className="w-2 h-2 rounded-full bg-accent animate-pulse" />
            <span className="text-sm font-medium text-foreground">AI Visibility Platform</span>
          </motion.div>

          <h1 className="text-display-sm md:text-display font-bold mb-8 text-foreground">
            Be found by AI.
            <br />
            <span className="text-gradient">Win more clients.</span>
          </h1>

          <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-12 leading-relaxed">
            ChatGPT, Perplexity, and Gemini are answering questions your clients ask — but they're not recommending you.
            <br /><br />
            Clientory is an AI visibility platform that helps professional services firms appear in answers generated by AI systems like ChatGPT and Perplexity.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <a href={clientoryAppUrl}>
              <Button size="lg" className="text-base px-8 h-14 rounded-full font-semibold shadow-lg shadow-primary/20 hover:shadow-xl hover:shadow-primary/30 transition-all duration-300">
                Try It Now
                <ArrowRight className="w-4 h-4 ml-2" />
              </Button>
            </a>
          </div>

          {/* Dashboard animation */}
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.6, duration: 0.8, ease: [0.25, 0.4, 0.25, 1] }}
            className="mt-16"
          >
            <AIDashboard />
          </motion.div>

          {/* Social proof */}
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 1.2, duration: 0.6 }}
          className="mt-12 pt-8 border-t border-border/50">
            
            <p className="text-sm text-muted-foreground">
              Designed for owners of small law, accounting, marketing, consulting, and other professional services firms.
            </p>
          </motion.div>
        </motion.div>
      </div>
    </section>);

};

export default Hero;
